### ISSUE TITLE
set up database

### ISSUE THREAD

**Issue by Yelroc** [nite-shayde/joke-me-off#5]
- decide DBMS (MySQL or Postgres)

- [https://dbdesigner.page.link/7CbjkXKfm3ipxzKX7](url)
- file: database/index.js
- file: database/schema.sql

**Comment by jesseLessinger** [comment]
1. let's add a 'zip_code' to user schema
2.  and a 'type' field to messages (like plain text, video, img, etc) and maybe change the 'text' field to 'content'
